### ISSUE TITLE
Ambiguous requirements

### ISSUE THREAD

**Issue by sporifolous** [freeCodeCamp/boilerplate-project-exercisetracker#13]
The requirements for this exercise are frustratingly ambiguous. 

Like number 2: "I can get an array of all users by getting api/exercise/users with the same info as when creating a user."

Getting with info? That sounds like we're asked to post data with a GET somehow. Is this supposed to mean that it will _return_ the same info as is posted to create a new user?

And 3: "I can add an exercise to any user by posting form data userId(_id), description, duration, and optionally date to /api/exercise/add."

What does "userId(_id)" mean? That we should post a `userId` argument, and it will be a MongoDB `_id`? 
Should duration be a number? I assume so based on the form requesting minutes for that field.

And 4: "Return will be the user object with added array log and count (total exercise count)."

Does this mean we should include the log array and the count _within_ the user object? Or do we return an object containing the user and these other properties?

**Comment by KaustubhD** [comment]
> Like number 2: "I can get an array of all users by getting api/exercise/users with the same info as when creating a user."

I'll be writing as the service user (not the developer)
It just means that the information in each of the many user's array will be the same what we get when we create a new user i.e. *_id* and *name*

> I assume so based on the form requesting minutes for that field

Yes, duration is in fact a **Number**
Even says so on the [project page](https://fuschia-custard.glitch.me/)

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
